services:
  - type: web
    name: rag-demo-frontend
    env: node
    repo: https://github.com/Hessa-Alharbi/rag-demo.git
    buildCommand: cd crewflow-rag-main/Navid-cloud-main/mulhem && npm install && npm run build
    startCommand: cd crewflow-rag-main/Navid-cloud-main/mulhem && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://rag-demo-backend.onrender.com
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
    autoDeploy: true
  
  - type: web
    name: rag-demo-backend
    env: python
    repo: https://github.com/Hessa-Alharbi/rag-demo.git
    buildCommand: cd Navid-RAG-ARC && pip install -r requirements.txt
    startCommand: cd Navid-RAG-ARC && python app.py
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
