services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     - VITE_API_URL=${API_URL:-http://localhost:8000}
  #   depends_on:
  #     - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   environment:
  #     - VLLM_API_URL=http://vllm:8000
  #   depends_on:
  #     - vllm

  # vllm:
  #   image: vllm/vllm-openai:latest
  #   ports:
  #     - "8080:8000"
  #   env_file:
  #     - .env
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   volumes:
  #     - ~/.cache/huggingface:/root/.cache/huggingface
  #   environment:
  #     - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
  #   command: --model CohereForAI/c4ai-command-r7b-12-2024
  #   ipc: host
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  redis-data:
